### ISSUE TITLE
SVG Logo

### ISSUE THREAD

**Issue by Chameera-de** [Tasin5541/portfolio#2]
Can you please tell me the way to create the logo SVG?

**Comment by Tasin5541** [comment]
Can you give a screenshot of the logo you're speaking of?

**Comment by Chameera-de** [comment]
<img width="389" alt="Screenshot 2021-06-11 at 18 22 33" src="https://user-images.githubusercontent.com/66526842/121689280-0b8ad680-cae2-11eb-9a5d-64734b90df91.png">
This one

**Comment by Tasin5541** [comment]
It's not a svg. It's plain text and css. You can find it in `src/components/header.js`

**Comment by Chameera-de** [comment]
<img width="389" alt="Screenshot 2021-06-11 at 18 51 19" src="https://user-images.githubusercontent.com/66526842/121692830-1d6e7880-cae6-11eb-94c7-d5b49558f72b.png">
how to create a image like this bro

**Comment by Tasin5541** [comment]
I used `ultimate background remover` to remove the background, `infinite painter` to create the orange background. All on mobile.
You could use photoshop on pc.
